version: '3.9'

services:
    db:
      container_name: tg_db
      image: postgres:14-alpine
      restart: always
      ports:
        - '5432:5432'
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: telega_db
      volumes:
        - ./postgres_data:/var/lib/postgresql/data

    pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: mastertixon.is@gmail.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - '5050:80'

    redis:
      image: redis:latest
      container_name: redis
      restart: always
      ports:
        - "6379:6379"
      volumes:
        - ./redis_data:/root/redis
        - ./redis_data/redis.conf:/usr/local/etc/redis/redis.conf
